spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/nova
    username: postgres
    password: postgres
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    hibernate:
      ddl-auto: create-drop  # 또는 update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
