spring:
  application:
    name: querydsl
  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: soddong
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

